nameOverride: ""
fullnameOverride: ""
image:
  repository: ghcr.io/sillock-inc/dotbot
  tag: null
  pullPolicy: IfNotPresent
resources:
  limits:
    memory: "500Mi"
    cpu: 500m
ingress:
  enabled: false