apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotbot
spec:
  selector:
    matchLabels:
      app: dotbot
  template:
    metadata:
      labels:
        app: dotbot
    spec:
      containers:
      - name: dotbot
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: Always
        resources:
          limits:
            memory: "1Gi"
            cpu: 1
        env:
        {{- with .Values.extraEnv }}
        {{- toYaml . | nindent 12 }}
        {{- end }}
        resources:
        {{- with .Values.resources }}
        {{- toYaml . | nindent 12 }}
        {{- end }}